{
 "title": "Ad Platform Metrics",
 "time": { "from": "1969-12-28T23:11:02.000Z", "to": "1970-01-04T00:49:10.000Z" },
 "panels": [
  {
   "title": "Impressions, Clicks & CTR",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toString(created_at) AS time,\r\n    SUM(impressions_count) AS impressions_count_total,\r\n    SUM(clicks_count) AS clicks_count_total,\r\n    clicks_count_total / impressions_count_total * 100 as ctr\r\n\r\nFROM \r\n(\r\n    SELECT \r\n        created_at, \r\n        COUNT(*) AS impressions_count,\r\n        0 AS clicks_count\r\n    FROM \r\n        impressions\r\n    GROUP BY \r\n        created_at\r\n\r\n    UNION ALL\r\n\r\n    SELECT \r\n        created_at, \r\n        0 AS impressions_count,\r\n        COUNT(*) AS clicks_count\r\n    FROM \r\n        clicks\r\n    GROUP BY \r\n        created_at\r\n)\r\nGROUP BY \r\n    time\r\nORDER BY \r\n    time\r\n"
    }
   ]
  },
  {
   "title": " Revenue Analysis: Impressions, clicks and total revenue",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toString(created_at) AS time,\r\n    SUM(impressions_income) AS impressions_income_total,\r\n    SUM(clicks_income) AS clicks_income_total,\r\n    (clicks_income_total + impressions_income_total) as total_income\r\nFROM \r\n(\r\n    SELECT \r\n        created_at, \r\n        SUM(cost_per_impression) AS impressions_income,\r\n        0 AS clicks_income\r\n    FROM \r\n        impressions\r\n    GROUP BY \r\n        created_at\r\n\r\n    UNION ALL\r\n\r\n    SELECT \r\n        created_at, \r\n        0 AS impressions_income,\r\n        SUM(cost_per_click) AS clicks_income\r\n    FROM \r\n        clicks\r\n    GROUP BY \r\n        created_at\r\n)\r\nGROUP BY \r\n    time\r\nORDER BY \r\n    time"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    created_at as day,\r\n    SUM(clicks_count) AS clicks_count\r\nFROM \r\n\r\n(\r\n    SELECT \r\n        created_at, \r\n        COUNT(*) AS clicks_count\r\n    FROM \r\n        clicks\r\n    GROUP BY \r\n        created_at\r\n)\r\nGROUP BY \r\n    day\r\nORDER BY \r\n    day"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    created_at as day,\r\n    SUM(impressions_count) AS impressions_count\r\nFROM \r\n(\r\n    SELECT \r\n        created_at, \r\n        COUNT(*) AS impressions_count\r\n    FROM \r\n        impressions\r\n    GROUP BY \r\n        created_at\r\n)\r\nGROUP BY \r\n    day\r\nORDER BY \r\n    day"
    }
   ]
  }
 ]
}