services:
  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  db:
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=prod
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d prod -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis
    image: 'redis:latest'
    command: redis-server --requirepass password --port 6380
    expose:
      - 6380
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "-p", "6380", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8123/ping || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: bitnami/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: root-user
      MINIO_ROOT_PASSWORD: root-password
      MINIO_USE_SSL: false
      MINIO_DEFAULT_BUCKETS: bucket
    ports:
      - "9100:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    depends_on:
      - clickhouse

  bot:
    container_name: bot
    build: ./bot
    restart: always
    env_file:
      - ./bot/.env
    depends_on:
      bot_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot_db:
    container_name: bot_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=prod
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d prod -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_bot_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  postgres_bot_data:
  redis_data:
  clickhouse_data:
  grafana_data:
  minio_data:
